- name: play1
  hosts: local
  connection: local
  tasks:
  - name: hello from play 1 task 1
    ansible.builtin.debug:
     msg: "hello from play one task 1"

  - name: hello from play 2 task 2
    ansible.builtin.debug:
     msg: "hello from play one task 1"

- name: play2
  hosts: local
  connection: local
  tasks:
  - name: hello from play 2 task 1
    ansible.builtin.debug:
     msg: "hello from play one task 1"

  - name: hello from play 2 task 2
    ansible.builtin.debug:
     msg: "hello from play one task 2"
