- name: play level varibles
  hosts: local
  connection: local
  vars:
   course: ansible #global declaration
   duration: 10 hr
   TRAINER: sivakumar
  tasks:
  - name: print course details
    ansible.builtin.debug:
     msg: "hello {{ course }}, course duration {{ duration }},trainer {{ trainer }}"