- name: play level varibles
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: print course details
    ansible.builtin.debug:
     msg: "hello {{ course }}, course duration {{ duration }},trainer {{ trainer }}"

  - name: print course details
    ansible.builtin.debug:
     msg: "hello {{ course }}, course duration {{ duration }},trainer {{ trainer }}"   