-  name: printing conditions
   hosts: local
   connection: local
   vars:
    number: 78
   tasks:
   - name:
     ansible.builtin.debug:
      msg: "print less {{ number }} than 100"
     when: number < 100

   - name:
     ansible.builtin.debug:
      msg: "print grater {{ number }} than 100"
     when: number > 100