- name: looping statements
  hosts: local
  connection: local
  tasks:
  - name: loop passing 
    ansible.builtin.debug:
     msg: "hello {{ item }}"
    loop:
    - sivakumar
    - saivenkat
    - naveen
    - gurusri