- name: looping statements
  hosts: frontend
  become: yes
  tasks:
  - name: installing package
    ansible.builtin.package:
     name: "hello {{ item }}"
     state: installed
    loop:
    - nginx
    - zip
    - mysql

